# fly.toml app configuration file generated for cool-sun-2654 on 2023-11-07T21:27:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cool-sun-2654"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
